apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdk 34
    defaultConfig {
        applicationId 'com.obddroid'
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 20616
        versionName 'OBDroid'

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        lintOptions {
            // Override lint error on targetSdkVersion
            abortOnError false
        }

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
        }

        kotlinOptions {
            jvmTarget = "17" // Ensure consistency with JavaVersion.VERSION_17
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['src/java']
            resources.srcDirs = ['src/resources']
            manifest.srcFile 'src/AndroidManifest.xml'
        }
    }

    applicationVariants.configureEach { variant ->
        variant.resValue "string", "app_version", variant.versionName
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


    productFlavors {
    }
    lint {
        abortOnError false
    }
    namespace 'com.obddroid'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.fazecast:jSerialComm:2.10.4'
    implementation 'com.github.mik3y:usb-serial-for-android:3.9.0'
    implementation 'com.github.anastr:speedviewlib:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.material:material:1.11.0'

    // NHTSA VIN Decoder API dependencies
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.google.code.gson:gson:2.10.1'
}
